server:
  port: 8082

guns:
  swagger-open: false              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
  file-upload-ip-and-port: http://211.149.226.29:8081 #文件显示的地址加端口号
#  file-upload-path: /usr/local/fileData/     #文件上传目录(不配置的话为java.io.tmpdir目录) d:/tmp
  file-download-path: /usr/local/fileData/        #/usr/local/fileData d:/fileData
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 3600     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 1800  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: false       #热加载beetl模板，开发时候用

spring:
  profiles:
    active: dev # dev #dev #produce #local #@spring.active@ #切换正式环境需要需改登陆页面，部署内部测试环境需要修改dev的上传目录地址
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: true
     # additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB


redis:
  host: 47.101.63.222
  port: 56379
  password: root
servlet:
    multipart:
    max-file-size: 50MB
    max-request-size: 100MB

redisson:
  address: redis://47.101.63.222:56379



mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model
  global-config:
    db-config:
  field-strategy: not_null
log:
  path: store-logs

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://192.168.4.131:23336/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: kakacldb2018u
    filters: wall,mergeStat

#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    url: jdbc:mysql://192.168.4.131:23336/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: kakacldb2018u
    dataSourceNames:
    - dataSourceGuns
    - dataSourceBiz

---

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://211.149.226.29:3306/db_kakacl?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: db_kakacl
    password: kakacl2018u
    filters: wall,mergeStat
