server:
  port: 8081

guns:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
  file-upload-ip-and-port: http://192.168.4.170:8081 #文件显示的地址加端口号
  file-upload-path: /usr/local/fileData #/usr/local/fileData   #文件上传目录(不配置的话为java.io.tmpdir目录) d:/fileData
  file-download-path: /usr/local/fileData #/usr/local/fileData d:/fileData
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 3600     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 1800  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用

spring:
  profiles:
    active: test #dev #produce #produce
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model

log:
  path: store-logs

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://qdm16219853.my3w.com:3306/qdm16219853_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: qdm16219853
    password: Ww120124wW.
    filters: wall,mergeStat

#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    url: jdbc:mysql://192.168.4.131:23336/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: kakacldb2018u
    dataSourceNames:
    - dataSourceGuns
    - dataSourceBiz

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://qdm16219853.my3w.com:3306/qdm16219853_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: qdm16219853
    password: Ww120124wW.
    filters: wall,mergeStat

#---
#
#spring:
#  profiles: dev
#  datasource:
#    url: jdbc:mysql://qdm16219853.my3w.com:3306/qdm16219853_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: qdm16219853
#    password: Ww120124wW.
#    filters: wall,mergeStat


